import time
from selenium import webdriver
from selenium.webdriver.common.by import By

# ID
chrome = webdriver.Chrome()
chrome.maximize_window()
chrome.get('https://www.phptravels.net/')
time.sleep(3)
chrome.find_element(By.ID,'cars-tab').click()
time.sleep(2)
chrome.find_element(By.ID,'visa-tab').click()
time.sleep(2)
chrome.find_element(By.ID,'ACCOUNT').click()
time.sleep(2)
chrome.quit()

# Link Text
chrome = webdriver.Chrome()
chrome.maximize_window()
chrome.get('https://www.phptravels.net/')
time.sleep(2)
chrome.find_element(By.LINK_TEXT,'Tours').click()
time.sleep(1)
chrome.back()
chrome.find_element(By.LINK_TEXT,'Blog').click()
time.sleep(1)
chrome.back()
chrome.find_element(By.LINK_TEXT,'Flights').click()
time.sleep(1)
chrome.quit()

# Partial link text
chrome = webdriver.Chrome()
chrome.maximize_window()
chrome.get('https://www.phptravels.net/')
time.sleep(2)
chrome.find_element(By.PARTIAL_LINK_TEXT,'Hot').click()
time.sleep(1)
chrome.back()
chrome.find_element(By.PARTIAL_LINK_TEXT,'Tran').click()
time.sleep(1)
chrome.back()
chrome.find_element(By.PARTIAL_LINK_TEXT,'Off').click()
chrome.back()
chrome.quit()

# Name
chrome = webdriver.Chrome()
chrome.maximize_window()
chrome.get('https://www.techlistic.com/p/selenium-practice-form.html')
time.sleep(2)
chrome.find_element(By.ID,'ez-accept-all').click()
chrome.find_element(By.NAME, 'firstname').send_keys('Ana')
time.sleep(1)
chrome.find_element(By.NAME, 'lastname').send_keys('Maria')
time.sleep(1)
lista_g = chrome.find_elements(By.NAME, 'sex')
lista_g[1].click()
time.sleep(1)
chrome.quit()

# Tag
chrome = webdriver.Chrome()
chrome.maximize_window()
chrome.get('https://formy-project.herokuapp.com/autocomplete')
time.sleep(2)
lista = chrome.find_elements(By.TAG_NAME, 'input')
lista[3].send_keys('Alexander City')
time.sleep(1)
lista[4].send_keys('Alabama')
time.sleep(1)
lista[6].send_keys('USA')
time.sleep(1)
chrome.quit()

# Class name
chrome = webdriver.Chrome()
chrome.maximize_window()
chrome.get('https://formy-project.herokuapp.com/')
time.sleep(2)
chrome.find_element(By.CLASS_NAME, 'btn').click()
time.sleep(1)
chrome.back()
links = chrome.find_elements(By.CLASS_NAME, 'btn')
links[1].click()
time.sleep(1)
chrome.back()
links = chrome.find_elements(By.CLASS_NAME, 'btn')
links[2].click()
time.sleep(1)
chrome.back()
time.sleep(2)
chrome.quit()

# CSS
chrome = webdriver.Chrome()
chrome.maximize_window()
chrome.get('https://the-internet.herokuapp.com/login')
time.sleep(2)
chrome.find_element(By.CSS_SELECTOR, 'input#username').send_keys('tomsmith')
time.sleep(2)
chrome.find_element(By.CSS_SELECTOR, 'div input[type="password"').send_keys('SuperSecretPassword!')
time.sleep(2)
chrome.find_element(By.CSS_SELECTOR, 'button.radius').click()
time.sleep(2)
chrome.quit()